### ISSUE TITLE
Detail view of an experiment

### ISSUE THREAD

**Issue by chovanecm** [chovanecm/sacredboard#4]
I want to see more details about selected experiment, especially  
- [x] config parameters (as the first option)
- [x] the full captured output of the programme (stored in the database)
- [ ] fields [define_them_here]
- [ ] an interactive browser of the object tree in the database ( issue #5 )
- [ ] a simple graph of [_define_what_ like accuracy etc (issue #6 )
- [ ] a link to start tensorboard if the experiment used that framework (issue #7 )

**Comment by chovanecm** [comment]
more or less implemented
