### ISSUE TITLE
Plotly plotter

### ISSUE THREAD

**Issue by chovanecm** [chovanecm/sacredboard#55]
As a Sacredboard developer, I want to have a convenient way to draw multiple time series onto a single canvas (Plotly) so that I can display e.g. data of the [Metrics API](http://sacred.readthedocs.io/en/latest/collected_information.html#metrics-api)

**Comment by chovanecm** [comment]
The result should be a HTML component that can plot several series at once.
- [ ] The x and y axes must have a definable label
- [ ] Each of the series must have a definable label
- [ ] It must be possible to dynamically add/hide series

**Comment by chovanecm** [comment]
The component should be defined as:
```html
<plot params="series: [series1, series2, series3], xLabel='x label', yLabel='y label'"></plot>
```

where `series1...seriesN` are initial series to be displayed, each of them having properties
```javascript
{x: [0, 1, 2,...], y: [10,20,30,...], label: "a data series"}
```

**Comment by chovanecm** [comment]
Test scenario (in-code):
You can use the test page (http://127.0.0.1:5000/static/scripts/plot/test.html).
1. Create the `<plot>` element with an observable array of series that have the x andy elements defined as well as observable arrays. The xLabel and yLabel of the chart as well as the label of the series are observables too. (defined as `ko.observable(value)` or (`ko.observableArray([])`)
2. e.g. in the developer console set different values for axes labels
3. remove one of the series, then the other, and re-add them to the observable array in the reverse direction (so that the first one that was removed is added back to the chart first)
