### ISSUE TITLE
Deleting an Experiment Run

### ISSUE THREAD

**Issue by chovanecm** [chovanecm/sacredboard#64]
The user indicates he wants to delete a particular experiment run.
1. The user selects the experiment to delete. (by opening its detail view).
2. The system shows a delete option in the detail view. (left-bottom under the menu).
3. The tells the system to delete the experiment. (clicking on a delete button in the left-bottom)
4. The system verifies the intention to delete the experiment. (a confirmation dialog)
5. The user confirms his choice.
6. The system deletes the run. (invoking DELETE on `/api/run/<id>`, which also deletes corresponding metrics, fs.files, and all other related entries).
7. The system closes the detail view.
8. The system removes the run from the table.

Postconditions:
1. [x] The run is deleted.
2. [x] Related metrics are deleted.
3. [ ] Related sources are deleted.
4. [ ] Related artifacts are deleted.

## Alternative scenarios
5. - The user does not confirm the choice - the run won't be deleted. (Postconditions do not apply)
6. - The run couldn't be deleted. The user is informed with an alert box.

**Comment by timmeinhardt** [comment]
Is this still in progress?

**Comment by chovanecm** [comment]
It's partially implemented - only the run itself and its metrics (if used) are deleted. Some garbage (like sources and artifacts) are not deleted, though.
It's in the development version:
`pip install https://github.com/chovanecm/sacredboard/archive/develop.zip`

When I will have time to finish it, is currently unclear :-(

**Comment by timmeinhardt** [comment]
I just installed the develop version but there is still no button to delete a run. Maybe I am overlooking something.

**Comment by chovanecm** [comment]
Should be in the experiment detail view, I just checked it:
![delete](https://user-images.githubusercontent.com/3611258/33151325-eff18df0-cfd7-11e7-9ae2-2aba2ffa4fe5.png)

**Comment by DennisSoemers** [comment]
I just also installed the develop version. The DELETE button does not show up if I view sacredboard in Firefox, but it does show up in Google Chrome @timmeinhardt

**Comment by timmeinhardt** [comment]
After reinstalling it a second time the button showed up as well. Maybe Chrome was still using a cached version or something. Thank you. Works quite well so far!

**Comment by DennisSoemers** [comment]
Ah yes. Hitting F5 to refresh made it also show up for me in Firefox, so probably indeed due to caching.

**Comment by timmeinhardt** [comment]
Why is this closed? Related artefacts and sources are not yet deleted.

**Comment by chovanecm** [comment]
My fault, I wanted to split it into several issues so that I can close each of them but now I realize I can keep this as a "parent" task.
But I think I put it into "icebox" then because I don't currently plan to work on it.
